<?php
/**
 *
 */
namespace  app\models;

use  \yii\base\Model;
class UserModel extends Model
{
    public  function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }

}